# Modified from https://github.com/sgmarz/osblog which is copyrighted by
# Stephen Marz and licensed under MIT.

[package]
name = "rust-riscv64-qemu-starter"
version = "0.1.0"
authors = ["Kayce Basques <kaycebasques@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
